apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: database
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/IceBreaker8/argocd-test
      revision: main
      directories:
      - path: infra/database/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/IceBreaker8/argocd-test
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: 
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true