apiVersion: v2
name: kube-prometheus-stack
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 68.2.1 # Use the version compatible with your Kubernetes cluster
    repository: https://prometheus-community.github.io/helm-charts
