apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: argocd-gateway
      namespace: argocd
  hostnames:
    - "prod-argocd.icedev.tn"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 443
          weight: 1
