configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
crds:
  install: true
  # -- Keep CRDs on chart uninstall
  keep: false

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  replicas: 2
