configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
crds:
  install: true
  # -- Keep CRDs on chart uninstall
  keep: false

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2
