apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 12.5.4
    releaseName: postgresql
    namespace: postgres
    valuesFile: values.yaml

namespace: postgres

resources:
  - ns.yaml
