apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-gateway.yaml

helmCharts:
  - name: nginx-gateway-fabric
    repo: oci://ghcr.io/nginx/charts
    version: 0.0.0-edge
    releaseName: nginx-gateway-fabric
    namespace: nginx-gateway
    valuesFile: values.yaml
    includeCRDs: true
