apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nginx-gateway-fabric
    repo: oci://ghcr.io/nginxinc/charts
    version: v1.5.1
    releaseName: nginx-gateway-fabric
    namespace: nginx-gateway
    valuesFile: nginx-values.yaml
