apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nginx-gateway-fabric
    repo: oci://ghcr.io/nginxinc/charts
    version: 0.0.0-edge
    releaseName: nginx-gateway-fabric
    namespace: nginx-gateway
    valuesFile: values.yaml
    includeCRDs: true
