apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nginx-gateway-fabric
    version: 1.5.1
    repo: oci://ghcr.io/nginxinc/charts
    releaseName: nginx-gateway-fabric
    namespace: nginx-gateway-fabric
    valuesFile: values.yaml
