apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nginx-gateway-fabric
    repo: https://charts.jetstack.io
    version: 1.5.1
    releaseName: nginx-gateway-fabric
    namespace: nginx-gateway
    valuesFile: values.yaml
