apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nginx-gateway-fabric
    repo: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
    version: "1.5.1"
    releaseName: nginx-gateway-fabric
    namespace: nginx-gateway
    valuesFile: values.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10" # Set the default sync wave to 0 for all resources
